### PR TITLE
Form

### PR DESCRIPTION
**Pull request by BethField**
Added styles, made header and footer uniform with other pages, added function sendUserData

### CODE REVIEW

**Review by emmamarks27 — APPROVED** [review]
Looks good!

**Review by Samupaga — CHANGES_REQUESTED** [review]
- I would suggest changing name of the link from "Enter" to "Next" as enter makes it sound like you are submitting the form.

- I would move the submit button to outside the container and have it a the bottom of the page (personal preference, happy to be overruled).

- Have some padding between the text and the container border (leftmost), text currently looks squashed together.

-Make elements responsive to different phone types as text leaks out of the container

**Review by fsaiz97 — APPROVED** [review]
Looks good

**Review by Samupaga — APPROVED** [review]
Everything seems to be in order

**Pull request merged**
